<li><a href="{{route('about')}}">О компании</a></li>
<li><a href="{{route('brands')}}">Бренды</a></li>
<li><a href="{{route('aktsii')}}">Акции</a></li>
<li><a href="{{route('pay')}}">Оплата</a></li>
<li><a href="{{route('garantia')}}">Гарантия</a></li>
<li><a href="{{route('vozvrat')}}">Возврат</a></li>
<li><a href="#">Укомплектуем дизайн-проект</a></li>
<li><a href="{{route('for_designers')}}">Дизайнерам</a></li>
<li><a href="{{route('opt_sotrudnihestvo')}}">Оптовым покупателям</a></li>
<li><a href="{{route('contacts')}}">Контакты</a></li>
